// This file exports neighborhood data for use throughout the site
export const neighborhoods = [
  {
    name: "Battery Park",
    description:
      "A historic neighborhood in Richmond's Northside known for its beautiful park, tree-lined streets, and mix of historic and modern homes.",
    services: [
      "Lawn Mowing",
      "Window Cleaning",
      "Pressure Washing",
      "Deck Staining",
      "Deck Painting",
      "Deck Sanding",
      "Carpet Cleaning",
      "Mobile Car Detailing",
      "Garden Weeding",
      "Pet Waste Removal",
      "Grill Steaming",
      "Flower Bed Maintenance",
    ],
    image:
      "https://i0.wp.com/rerva.com/wp-content/uploads/2017/10/battery-park-thumbnail.jpg?fit=1200%2C1200&quality=99&ssl=1",
    fallbackImage:
      "https://i0.wp.com/rerva.com/wp-content/uploads/2017/10/battery-park-thumbnail.jpg?fit=1200%2C1200&quality=99&ssl=1",
    slug: "battery-park",
  },
  {
    name: "Bellevue",
    description:
      "A charming neighborhood with historic homes, tree-lined streets, and a vibrant commercial district along MacArthur Avenue.",
    services: [
      "Lawn Mowing",
      "Window Cleaning",
      "Pressure Washing",
      "Deck Staining",
      "Deck Painting",
      "Deck Sanding",
      "Carpet Cleaning",
      "Mobile Car Detailing",
      "Garden Weeding",
      "Pet Waste Removal",
      "Grill Steaming",
      "Flower Bed Maintenance",
    ],
    image: "https://www.bellevueweb.org/wp-content/uploads/2017/08/Arch-1024x640.jpg",
    fallbackImage: "https://www.bellevueweb.org/wp-content/uploads/2017/08/Arch-1024x640.jpg",
    slug: "bellevue",
  },
  {
    name: "Laburnum Park",
    description:
      "A residential neighborhood featuring early 20th century homes with distinctive architectural styles and beautiful landscaping.",
    services: [
      "Lawn Mowing",
      "Window Cleaning",
      "Pressure Washing",
      "Deck Staining",
      "Deck Painting",
      "Deck Sanding",
      "Carpet Cleaning",
      "Mobile Car Detailing",
      "Garden Weeding",
      "Pet Waste Removal",
      "Grill Steaming",
      "Flower Bed Maintenance",
    ],
    image: "https://upload.wikimedia.org/wikipedia/commons/6/6f/Laburnum_park.jpg",
    fallbackImage: "https://upload.wikimedia.org/wikipedia/commons/6/6f/Laburnum_park.jpg",
    slug: "laburnum-park",
  },
  {
    name: "Ginter Park",
    description:
      "A historic neighborhood with grand homes, wide boulevards, and mature trees, developed by Lewis Ginter in the late 19th century.",
    services: [
      "Lawn Mowing",
      "Window Cleaning",
      "Pressure Washing",
      "Deck Staining",
      "Deck Painting",
      "Deck Sanding",
      "Carpet Cleaning",
      "Mobile Car Detailing",
      "Garden Weeding",
      "Pet Waste Removal",
      "Grill Steaming",
      "Flower Bed Maintenance",
    ],
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRCTLYr2SGmkEgUf28vq1sMVX26jHIpwfMMyw&s",
    fallbackImage: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRCTLYr2SGmkEgUf28vq1sMVX26jHIpwfMMyw&s",
    slug: "ginter-park",
  },
  {
    name: "Sherwood Park",
    description:
      "A quiet residential neighborhood with well-maintained homes, friendly neighbors, and convenient access to amenities.",
    services: [
      "Lawn Mowing",
      "Window Cleaning",
      "Pressure Washing",
      "Deck Staining",
      "Deck Painting",
      "Deck Sanding",
      "Carpet Cleaning",
      "Mobile Car Detailing",
      "Garden Weeding",
      "Pet Waste Removal",
      "Grill Steaming",
      "Flower Bed Maintenance",
    ],
    image:
      "https://imagescdn.homes.com/i2/L6w6nowQSHlpWMMzpikUlMf6jkVNJU75HY_yVKIk3UE/117/sherwood-park-richmond-va-2.jpg?p=1",
    fallbackImage:
      "https://imagescdn.homes.com/i2/L6w6nowQSHlpWMMzpikUlMf6jkVNJU75HY_yVKIk3UE/117/sherwood-park-richmond-va-2.jpg?p=1",
    slug: "sherwood-park",
  },
  {
    name: "Rosedale",
    description:
      "A diverse neighborhood with a mix of housing styles, community gardens, and a strong sense of community.",
    services: [
      "Lawn Mowing",
      "Window Cleaning",
      "Pressure Washing",
      "Deck Staining",
      "Deck Painting",
      "Deck Sanding",
      "Carpet Cleaning",
      "Mobile Car Detailing",
      "Garden Weeding",
      "Pet Waste Removal",
      "Grill Steaming",
      "Flower Bed Maintenance",
    ],
    image:
      "https://i0.wp.com/rerva.com/wp-content/uploads/2019/08/rosedale-10-of-28_48568238361_o-1024x683.jpg?resize=880%2C587&quality=99&ssl=1",
    fallbackImage:
      "https://i0.wp.com/rerva.com/wp-content/uploads/2019/08/rosedale-10-of-28_48568238361_o-1024x683.jpg?resize=880%2C587&quality=99&ssl=1",
    slug: "rosedale",
  },
  {
    name: "Bryan Parkway",
    description:
      "A picturesque neighborhood with distinctive homes, landscaped medians, and a strong community spirit.",
    services: [
      "Lawn Mowing",
      "Window Cleaning",
      "Pressure Washing",
      "Deck Staining",
      "Deck Painting",
      "Deck Sanding",
      "Carpet Cleaning",
      "Mobile Car Detailing",
      "Garden Weeding",
      "Pet Waste Removal",
      "Grill Steaming",
      "Flower Bed Maintenance",
    ],
    image:
      "https://images1.apartments.com/i2/W3KY6R7yhomOvHx4HiMGIDHwH6U3JtWF3bBCRhI6PrE/111/randolph-village-richmond-va-primary-photo.jpg", // Using Randolph image as Bryan Parkway wasn't specifically provided
    fallbackImage:
      "https://images1.apartments.com/i2/W3KY6R7yhomOvHx4HiMGIDHwH6U3JtWF3bBCRhI6PrE/111/randolph-village-richmond-va-primary-photo.jpg",
    slug: "bryan-parkway",
  },
  {
    name: "The Fan",
    description:
      "Historic district known for beautiful architecture and tree-lined streets with a vibrant mix of residential and commercial spaces.",
    services: [
      "Lawn Mowing",
      "Window Cleaning",
      "Pressure Washing",
      "Deck Staining",
      "Deck Painting",
      "Deck Sanding",
      "Carpet Cleaning",
      "Mobile Car Detailing",
      "Garden Weeding",
      "Pet Waste Removal",
      "Grill Steaming",
      "Flower Bed Maintenance",
    ],
    image: "https://homesweetrva.com/wp-content/uploads/2021/12/the-fan-community-1024x683.jpg",
    fallbackImage: "https://homesweetrva.com/wp-content/uploads/2021/12/the-fan-community-1024x683.jpg",
    slug: "the-fan",
  },
  {
    name: "Church Hill",
    description: "One of Richmond's oldest neighborhoods with stunning views of downtown and historic significance.",
    services: [
      "Lawn Mowing",
      "Window Cleaning",
      "Pressure Washing",
      "Deck Staining",
      "Deck Painting",
      "Deck Sanding",
      "Carpet Cleaning",
      "Mobile Car Detailing",
      "Garden Weeding",
      "Pet Waste Removal",
      "Grill Steaming",
      "Flower Bed Maintenance",
    ],
    image:
      "https://imagescdn.homes.com/i2/kSnu8UIFw1AVGCkh3r1Roh7j9bJPVHHy2-ku_UYjoXA/117/church-hill-richmond-va.jpg?p=1",
    fallbackImage:
      "https://imagescdn.homes.com/i2/kSnu8UIFw1AVGCkh3r1Roh7j9bJPVHHy2-ku_UYjoXA/117/church-hill-richmond-va.jpg?p=1",
    slug: "church-hill",
  },
  {
    name: "Museum District",
    description: "Cultural hub with beautiful homes and proximity to museums, featuring a mix of architectural styles.",
    services: [
      "Lawn Mowing",
      "Window Cleaning",
      "Pressure Washing",
      "Deck Staining",
      "Deck Painting",
      "Deck Sanding",
      "Carpet Cleaning",
      "Mobile Car Detailing",
      "Garden Weeding",
      "Pet Waste Removal",
      "Grill Steaming",
      "Flower Bed Maintenance",
    ],
    image: "https://upload.wikimedia.org/wikipedia/commons/6/6c/Richmondmuseumdistrict.jpg",
    fallbackImage: "https://upload.wikimedia.org/wikipedia/commons/6/6c/Richmondmuseumdistrict.jpg",
    slug: "museum-district",
  },
  {
    name: "Carytown",
    description:
      "Vibrant shopping district with unique homes and gardens, known for its eclectic mix of shops and restaurants.",
    services: [
      "Lawn Mowing",
      "Window Cleaning",
      "Pressure Washing",
      "Deck Staining",
      "Deck Painting",
      "Deck Sanding",
      "Carpet Cleaning",
      "Mobile Car Detailing",
      "Garden Weeding",
      "Pet Waste Removal",
      "Grill Steaming",
      "Flower Bed Maintenance",
    ],
    image:
      "https://static.wixstatic.com/media/910800_c0b4ff263af14dd6996191c04a4575db~mv2.jpg/v1/fill/w_640,h_538,al_c,q_80,usm_0.66_1.00_0.01,enc_avif,quality_auto/910800_c0b4ff263af14dd6996191c04a4575db~mv2.jpg",
    fallbackImage:
      "https://static.wixstatic.com/media/910800_c0b4ff263af14dd6996191c04a4575db~mv2.jpg/v1/fill/w_640,h_538,al_c,q_80,usm_0.66_1.00_0.01,enc_avif,quality_auto/910800_c0b4ff263af14dd6996191c04a4575db~mv2.jpg",
    slug: "carytown",
  },
  {
    name: "Scott's Addition",
    description:
      "Rapidly growing neighborhood with a mix of residential and commercial spaces, known for breweries and modern living.",
    services: [
      "Lawn Mowing",
      "Window Cleaning",
      "Pressure Washing",
      "Deck Staining",
      "Deck Painting",
      "Deck Sanding",
      "Carpet Cleaning",
      "Mobile Car Detailing",
      "Garden Weeding",
      "Pet Waste Removal",
      "Grill Steaming",
      "Flower Bed Maintenance",
    ],
    image:
      "https://assets.simpleviewinc.com/simpleview/image/upload/c_fill,f_jpg,h_698,q_65,w_640/v1/clients/richmond/Blue_Bee_Cider_Evening_jpg_d23ae761-fdda-4a68-8752-fcb2956441bb.jpg",
    fallbackImage:
      "https://assets.simpleviewinc.com/simpleview/image/upload/c_fill,f_jpg,h_698,q_65,w_640/v1/clients/richmond/Blue_Bee_Cider_Evening_jpg_d23ae761-fdda-4a68-8752-fcb2956441bb.jpg",
    slug: "scotts-addition",
  },
  {
    name: "Jackson Ward",
    description:
      "Historic neighborhood known as the 'Harlem of the South' with rich cultural heritage and distinctive architecture.",
    services: [
      "Lawn Mowing",
      "Window Cleaning",
      "Pressure Washing",
      "Deck Staining",
      "Deck Painting",
      "Deck Sanding",
      "Carpet Cleaning",
      "Mobile Car Detailing",
      "Garden Weeding",
      "Pet Waste Removal",
      "Grill Steaming",
      "Flower Bed Maintenance",
    ],
    image:
      "https://www.tclf.org/sites/default/files/thumbnails/image/VA_Richmond_JacksonWard_BarrettDoherty_2018_01.jpg",
    fallbackImage:
      "https://www.tclf.org/sites/default/files/thumbnails/image/VA_Richmond_JacksonWard_BarrettDoherty_2018_01.jpg",
    slug: "jackson-ward",
  },
  {
    name: "Shockoe Bottom",
    description:
      "Historic district with cobblestone streets, known for its nightlife, restaurants, and proximity to the James River.",
    services: [
      "Lawn Mowing",
      "Window Cleaning",
      "Pressure Washing",
      "Deck Staining",
      "Deck Painting",
      "Deck Sanding",
      "Carpet Cleaning",
      "Mobile Car Detailing",
      "Garden Weeding",
      "Pet Waste Removal",
      "Grill Steaming",
      "Flower Bed Maintenance",
    ],
    image:
      "https://static1.squarespace.com/static/595d39d2d482e940948f8507/t/5972ba123e00be4843d99554/1501290259257/?format=1500w",
    fallbackImage:
      "https://static1.squarespace.com/static/595d39d2d482e940948f8507/t/5972ba123e00be4843d99554/1501290259257/?format=1500w",
    slug: "shockoe-bottom",
  },
  {
    name: "Manchester",
    description:
      "Up-and-coming neighborhood across the James River with industrial charm and river views of the downtown skyline.",
    services: [
      "Lawn Mowing",
      "Window Cleaning",
      "Pressure Washing",
      "Deck Staining",
      "Deck Painting",
      "Deck Sanding",
      "Carpet Cleaning",
      "Mobile Car Detailing",
      "Garden Weeding",
      "Pet Waste Removal",
      "Grill Steaming",
      "Flower Bed Maintenance",
    ],
    image:
      "https://imagescdn.homes.com/i2/9fqaVrW8Xdq-BaklTFNQFt6pofHcINkt9qvoTQMaWWg/111/manchester-richmond-va.jpg?p=1",
    fallbackImage:
      "https://imagescdn.homes.com/i2/9fqaVrW8Xdq-BaklTFNQFt6pofHcINkt9qvoTQMaWWg/111/manchester-richmond-va.jpg?p=1",
    slug: "manchester",
  },
  {
    name: "Oregon Hill",
    description:
      "Historic working-class neighborhood near VCU with a tight-knit community and views of the James River.",
    services: [
      "Lawn Mowing",
      "Window Cleaning",
      "Pressure Washing",
      "Deck Staining",
      "Deck Painting",
      "Deck Sanding",
      "Carpet Cleaning",
      "Mobile Car Detailing",
      "Garden Weeding",
      "Pet Waste Removal",
      "Grill Steaming",
      "Flower Bed Maintenance",
    ],
    image:
      "https://www.dhr.virginia.gov/wp-content/uploads/2023/03/127-0362_Oregon_Hill_HD_2024_streetscape_VLR_CCL-scaled.jpg",
    fallbackImage:
      "https://www.dhr.virginia.gov/wp-content/uploads/2023/03/127-0362_Oregon_Hill_HD_2024_streetscape_VLR_CCL-scaled.jpg",
    slug: "oregon-hill",
  },
  {
    name: "Carver",
    description:
      "Historic neighborhood adjacent to VCU with a mix of students and long-time residents, featuring distinctive architecture.",
    services: [
      "Lawn Mowing",
      "Window Cleaning",
      "Pressure Washing",
      "Deck Staining",
      "Deck Painting",
      "Deck Sanding",
      "Carpet Cleaning",
      "Mobile Car Detailing",
      "Garden Weeding",
      "Pet Waste Removal",
      "Grill Steaming",
      "Flower Bed Maintenance",
    ],
    image: "https://upload.wikimedia.org/wikipedia/commons/4/4c/Carver_residential.JPG",
    fallbackImage: "https://upload.wikimedia.org/wikipedia/commons/4/4c/Carver_residential.JPG",
    slug: "carver",
  },
  {
    name: "Randolph",
    description:
      "Diverse neighborhood with a mix of historic and modern homes, close to Maymont Park and the James River.",
    services: [
      "Lawn Mowing",
      "Window Cleaning",
      "Pressure Washing",
      "Deck Staining",
      "Deck Painting",
      "Deck Sanding",
      "Carpet Cleaning",
      "Mobile Car Detailing",
      "Garden Weeding",
      "Pet Waste Removal",
      "Grill Steaming",
      "Flower Bed Maintenance",
    ],
    image:
      "https://images1.apartments.com/i2/W3KY6R7yhomOvHx4HiMGIDHwH6U3JtWF3bBCRhI6PrE/111/randolph-village-richmond-va-primary-photo.jpg",
    fallbackImage:
      "https://images1.apartments.com/i2/W3KY6R7yhomOvHx4HiMGIDHwH6U3JtWF3bBCRhI6PrE/111/randolph-village-richmond-va-primary-photo.jpg",
    slug: "randolph",
  },
  {
    name: "Woodland Heights",
    description:
      "Charming neighborhood south of the James River with tree-lined streets and a mix of architectural styles.",
    services: [
      "Lawn Mowing",
      "Window Cleaning",
      "Pressure Washing",
      "Deck Staining",
      "Deck Painting",
      "Deck Sanding",
      "Carpet Cleaning",
      "Mobile Car Detailing",
      "Garden Weeding",
      "Pet Waste Removal",
      "Grill Steaming",
      "Flower Bed Maintenance",
    ],
    image: "https://upload.wikimedia.org/wikipedia/commons/d/d6/3200_Block_Semmes_Avenue_Richmond_VA.JPG",
    fallbackImage: "https://upload.wikimedia.org/wikipedia/commons/d/d6/3200_Block_Semmes_Avenue_Richmond_VA.JPG",
    slug: "woodland-heights",
  },
  {
    name: "Forest Hill",
    description:
      "Scenic neighborhood with historic homes, mature trees, and proximity to Forest Hill Park and the James River.",
    services: [
      "Lawn Mowing",
      "Window Cleaning",
      "Pressure Washing",
      "Deck Staining",
      "Deck Painting",
      "Deck Sanding",
      "Carpet Cleaning",
      "Mobile Car Detailing",
      "Garden Weeding",
      "Pet Waste Removal",
      "Grill Steaming",
      "Flower Bed Maintenance",
    ],
    image: "https://upload.wikimedia.org/wikipedia/commons/f/f9/Springhill_Avenue_in_Forest_Hill.jpg",
    fallbackImage: "https://upload.wikimedia.org/wikipedia/commons/f/f9/Springhill_Avenue_in_Forest_Hill.jpg",
    slug: "forest-hill",
  },
  {
    name: "Westover Hills",
    description:
      "Established neighborhood with a mix of architectural styles, known for its community feel and proximity to the James River.",
    services: [
      "Lawn Mowing",
      "Window Cleaning",
      "Pressure Washing",
      "Deck Staining",
      "Deck Painting",
      "Deck Sanding",
      "Carpet Cleaning",
      "Mobile Car Detailing",
      "Garden Weeding",
      "Pet Waste Removal",
      "Grill Steaming",
      "Flower Bed Maintenance",
    ],
    image:
      "https://imagescdn.homes.com/i2/XzYBxDVV1Uhawz2jzpAWVN0mGdx62iWv3fsNXjJUc1M/117/westover-hills-richmond-va.jpg?p=1",
    fallbackImage:
      "https://imagescdn.homes.com/i2/XzYBxDVV1Uhawz2jzpAWVN0mGdx62iWv3fsNXjJUc1M/117/westover-hills-richmond-va.jpg?p=1",
    slug: "westover-hills",
  },
  {
    name: "Windsor Farms",
    description: "Upscale neighborhood with stately homes, designed with English village aesthetics and spacious lots.",
    services: [
      "Lawn Mowing",
      "Window Cleaning",
      "Pressure Washing",
      "Deck Staining",
      "Deck Painting",
      "Deck Sanding",
      "Carpet Cleaning",
      "Mobile Car Detailing",
      "Garden Weeding",
      "Pet Waste Removal",
      "Grill Steaming",
      "Flower Bed Maintenance",
    ],
    image:
      "https://st.hzcdn.com/simgs/pictures/exteriors/windsor-farms-richmond-va-jennifer-stoner-interiors-img~c871d8c302941cb9_4-5255-1-75d3c76.jpg",
    fallbackImage:
      "https://st.hzcdn.com/simgs/pictures/exteriors/windsor-farms-richmond-va-jennifer-stoner-interiors-img~c871d8c302941cb9_4-5255-1-75d3c76.jpg",
    slug: "windsor-farms",
  },
  {
    name: "Northside",
    description:
      "Collection of diverse neighborhoods north of downtown with a mix of historic and modern homes and strong community ties.",
    services: [
      "Lawn Mowing",
      "Window Cleaning",
      "Pressure Washing",
      "Deck Staining",
      "Deck Painting",
      "Deck Sanding",
      "Carpet Cleaning",
      "Mobile Car Detailing",
      "Garden Weeding",
      "Pet Waste Removal",
      "Grill Steaming",
      "Flower Bed Maintenance",
    ],
    image:
      "https://i0.wp.com/rerva.wpengine.com/wp-content/uploads/2017/10/battery-park-26-of-32_48746022513_o.jpg?quality=99",
    fallbackImage:
      "https://i0.wp.com/rerva.wpengine.com/wp-content/uploads/2017/10/battery-park-26-of-32_48746022513_o.jpg?quality=99",
    slug: "northside",
  },
]

export default neighborhoods
